### ISSUE TITLE
Add option for displaying footnotes at the bottom of the article

### ISSUE THREAD

**Issue by seankwilliams** [seankwilliams/modern-footnotes#11]
There have been several requests for displaying a list of footnotes at the bottom of the plugin. This issue is a summary of all the ideas around that request, but it can certainly be implemented in pieces instead of all at once.

Suggested implementation from @KZeni :  I imagine this could be implemented as an additional, self-contained, shortcode like [mfn-list] which then pulls all [mfn] shortcodes (with their content) from the content that [mfn-list] is also in. The list of footnotes is then output wherever that [mfn-list] shortcode is placed while leaving the existing inline shortcodes as-is (or potentially via a shortcode attribute a-la [mfn-list disable_inline="true"], but I could see that being something for a later version to maybe take-on after the core implementation.)

In addition to the suggested shortcode implementation, it would be good to have a configuration option to automatically display the footnote list at the bottom of every article (by default, this option should be off).

Also, there have been requests to display footnotes in this manner that respect the `<!–nextpage–>` tag and display footnotes like they are in books.

Consideration when developing this from https://wordpress.org/support/topic/fwiw/#post-12055070: "Thanks again for this great plugin. It plays well with the Divi theme we are using. Plugins that put the text at the bottom of the page are problematic with pages using the Divi Toggle module."

**Comment by seankwilliams** [comment]
An example of a plugin that does this functionality well, from https://wordpress.org/support/topic/list-of-footnotes/#post-12233328:

The one I used before was Easy Footnotes (https://wordpress.org/plugins/easy-footnotes/)
I left it because it wouldn’t work in mobile and was not being updated, but it is a nice plugin and does a good job of outputting “the full footnote text to the bottom of your post in an ordered list with a corresponding number”.

I would like to say that I like the idea of a list on the end of the article (I’m doing it manually just now, without links), but not at the cost of losing lightness or simplicity, that are two great things about your plugin!

**Comment by seankwilliams** [comment]
This task would also cover this request from https://wordpress.org/support/topic/print-footnotes-at-end-of-page/:

Are there easy ways to enable footnotes of Modern Footnotes to be printed at the end of a file (footer/end notes) rather than in-line? PDF print works well. Paper print, not so well.

PrintFriendly plugin is used on the blog — but I’m asking more generally so that any user that wants to print to paper may have the footnotes printed at the end of the section/page (footnotes/endnotes).

Printing footnotes inline is not fluid – and I don’t think URLs are included. It can be confusing to some readers, too.

**Comment by adamshand** [comment]
Thanks for all your work on this plugin, I love it!  I'd love an update to support this feature.  I sometimes use lots of footnotes and worry that readers miss them.  To have them all be listed explicitly would be very helpful.  Thanks again.

**Comment by seankwilliams** [comment]
Another request for this feature, with the ability to collapse/expand the list of footnotes at the bottom of the support: https://wordpress.org/support/topic/please-make/

**Comment by aandrewjoyce** [comment]
This would be much appreciated, so that we can output all footnotes at the end of a post (as well as showing within the popup). An automatic display option that would show up on any page with footnotes would be fantastic.

**Comment by Stimson** [comment]
Hi @seankwilliams -- we are using your plugin for our think tank's website and wish to register our support for this feature. Oftentimes academic readers want to print the full product out. Rather than have to create PDFs, it would be great if we could just drop the full list of footnotes into the bottom of our print view!

**Comment by seankwilliams** [comment]
Another suggestion on this from https://wordpress.org/support/topic/about-list-of-notes-on-the-end-of-page-an-idea/

```
I see that the question of a list of all notes on the page is still hot. I looked at other plugins that have this feature and discovered there is a big problem with placement. Ideally the list should follow just after the text, before references, but it looks like there is no way to do it programmatically and in fact the list ends placed well after the content, sometimes after social media and in one instance after related posts.
The solution I gave to it was simply do it the hard way, copying every note after the content, lol.
But I got thinking…
Would it be “doable” with a shortcode or something like it?
```
