### ISSUE TITLE
Screenreading and Accessibility 

### ISSUE THREAD

**Issue by gardinermichael** [seankwilliams/modern-footnotes#12]
Hi there,

This plugin is absolutely wonderful! I have a question for you -- if you're not sure of the answer, I'd be happy to look into it and report back. We were thinking of implementing your plugin, but my boss wanted to make sure the output played nicely with accessibility users and screen readers.

**Comment by KZeni** [comment]
Running https://squizlabs.github.io/HTML_CodeSniffer/ and/or https://wave.webaim.org on a page where a footnote is included could help determine the ADA & other accessibility standards support. I quick test showed my footnotes didn't have any errors with WCAG 2.0 AA compliance.

To take it a step further, I could see actually utilizing a screen reader to confirm the footnote is properly presented for the ideal outcome (I don't have one myself to test with at this time), and/or implementing aria-labels and/or titles for the footnote links & other accessibility-specific enhancements to just make it a bit better.

**Comment by seankwilliams** [comment]
Thanks @gardinermichael and @KZeni ! I'm actually not sure how the plugin plays with accessibility and screen readers, @gardinermichael, could you look into it and let me know what you find? I'm happy to implement any suggested changes for this.

**Comment by gardinermichael** [comment]
@KZeni @seankwilliams Thank you for your replies, I appreciate it! I'll look into this further with Apple's VoiceOver screen reader and report back.

**Comment by seankwilliams** [comment]
@gardinermichael thank you!

**Comment by gardinermichael** [comment]
Just wanted to update: Will be getting to this soon.

**Comment by seankwilliams** [comment]
No rush, thank you!

**Comment by seankwilliams** [comment]
I've reviewed the plugin and it was mostly good for accessibility and screen readers. The one area that needed improvement was how tooltips handle focus. The plugin is now updated so that the focus goes into the tooltip when opening a footnote and goes back to the footnote's link when closing a footnote. Also, now you can close an open tooltip with the Escape key.
