### ISSUE TITLE
Prevent line-height to change in lines with a footnote

### ISSUE THREAD

**Issue by larsschellhas** [seankwilliams/modern-footnotes#30]
In lines with a footnote, the line-height increases which causes a not-so-nice look when reading through a longer text.

I solved it by adding this CSS code:
`.modern-footnotes-footnote {line-height: initial;}`

this version seems to work equally:
`.modern-footnotes-footnote {line-height: normal;}`

**Comment by seankwilliams** [comment]
Thanks @larsschellhas ! I'll get this incorporated in a future release.

**Comment by larsschellhas** [comment]
Awesome! 😊
